config/routes.rb
Hello::Engine.routes.draw do
  # root 'management/profiles#show'

  #
  # REGISTRATION
  #
  scope module: 'registration' do
    get 'sign_up' => 'sign_up#index'
    post 'sign_up' => 'sign_up#create'
    get 'sign_up/widget' => 'sign_up#widget'
    match 'sign_up/disabled' => 'sign_up#disabled', via: [:get, :post]
  end

  #
  # AUTHENTICATION
  #
  scope module: 'authentication' do
    resources :sessions, only: [:index, :new, :show, :destroy]
    delete 'sign_out' => 'sessions#sign_out'

    get  'sign_in' => 'sign_in#index'
    post 'sign_in' => 'sign_in#authenticate'

    get 'sudo_mode' => 'sudo_mode#form'
    patch 'sudo_mode' => 'sudo_mode#authenticate'
    get 'sudo_mode/expire' => 'sudo_mode#expire'
  end

  #
  # MANAGEMENT
  #
  scope module: 'management' do
    resources :accesses, only: [:index, :destroy]

    root 'profiles#show'
    resource :profile, only: [:show, :update, :destroy] do
      member do
        get :cancel
      end
    end

    resources :emails, only: [:index, :create, :destroy] do
      member do
        post 'deliver'
        get 'confirm/:token' => 'confirm_emails#confirm', as: 'confirm'
      end
      collection do
        get 'expired_confirmation_token' => 'confirm_emails#expired_confirmation_token'
      end
    end

    resources :passwords, only: [:index, :show, :update] do
      collection do
        get 'forgot' => 'forgot_password#index'
        post 'forgot' => 'forgot_password#forgot'
      end
      member do
        scope '/reset/:user_id/:token' do
          get '/' => 'reset_password#index', as: 'reset'
          post '/' => 'reset_password#update', as: nil
        end
      end
    end
  end

  #
  # INTERNATIONALIZATION
  #
  scope module: 'internationalization' do
    get 'locale' => 'locale#index'
    post 'locale' => 'locale#update'
  end

end

app/controllers/hello/application_controller.rb
class Hello::ApplicationController < ApplicationController
  rescue_from Hello::Errors::JsonNotSupported do |exception|
    render json: _json_data_for_exception(exception), status: :bad_request
  end

  rescue_from ActionController::ParameterMissing do |exception|
    respond_to do |format|
      format.html { fail exception }
      format.json { render json: _json_data_for_exception(exception), status: :bad_request } # 400
    end
  end

  private

  # Don't override this at home, kids
  def _json_data_for_exception(exception)
    {
      maintenance: false,
      action:      "#{controller_name}##{action_name}",
      exception: {
        class:       exception.class.name,
        message:     exception.message,
        # backtrace:   exception.backtrace
      }
    }
  end
end

app/controllers/hello/authentication/sessions_controller.rb
module Hello
  module Authentication
    class SessionsController < ApplicationController
      dont_kick_people

      before_actions do
        only(:index) { @accesses = current_accesses }
        only(:show, :destroy) { @access = find_access! }
      end

      # GET /hello/sessions
      def index
        render_list
      end

      # GET /hello/sessions/new
      def new
        render_new
      end

      # GET /hello/sessions/1
      def show
        self.session_token = @access.token

        business = Hello::Business::Authentication::SignIn.new

        respond_to do |format|
          format.html { redirect_to hello.sessions_path, notice: business.success_message }
          format.json { head :reset_content }
        end
      end

      # DELETE /hello/sessions/1
      def destroy
        sign_out!(@access)

        business = Hello::Business::Authentication::SignOut.new

        respond_to do |format|
          format.html { redirect_to hello.sessions_path, notice: business.success_message }
          format.json { head :reset_content }
        end
      end

      # get /hello/sign_out
      def sign_out
        sign_out!

        business = Hello::Business::Authentication::SignOut.new

        respond_to do |format|
          format.html { redirect_to '/', notice: business.success_message }
          format.json { head :reset_content }
        end
      end

      private

      def find_access!
        current_accesses.find { |at| at.id.to_s == params[:id] } || access_not_found!
      end

      def access_not_found!
        # we can re use the sign out message here
        business = Hello::Business::Authentication::SignOut.new
        respond_to do |format|
          format.html { redirect_to hello.sessions_path, notice: business.success_message }
          format.json { head :reset_content }
        end
      end

      def render_list
        render 'hello/authentication/sessions'
      end

      def render_new
        render 'hello/authentication/new_session'
      end
    end
  end
end

app/controllers/hello/authentication/sign_in_controller.rb
module Hello
  module Authentication
    # you really should be overriding concerns instead of this file
    class SignInController < ApplicationController
      include Hello::Concerns::Authentication::SignIn

      kick :guest, only: [:authenticated]

      before_actions do
        only(:index, :authenticate) { @sign_in = Hello::Business::Authentication::SignIn.new }
      end

      # GET /hello/sign_in
      def index
        render_sign_in
      end

      # POST /hello/sign_in
      def authenticate
        if @sign_in.authenticate(sign_in_params[:login], sign_in_params[:password])
          flash[:notice] = @sign_in.success_message
          on_success
        else
          on_failure
        end
      end

      private

      def sign_in_params
        params.require(:sign_in)
      end

      def render_sign_in
        render 'hello/authentication/sign_in'
      end
    end
  end
end

app/controllers/hello/authentication/sudo_mode_controller.rb
module Hello
  module Authentication
    class SudoModeController < ApplicationController
      kick :guest, :onboarding

      # GET /hello/sudo_mode
      def form
        render_sudo_mode_form
      end

      # PATCH /hello/sudo_mode
      def authenticate
        business = Business::Authentication::SudoModeAuthentication.new(current_access)

        if business.authenticate!(password_param)
          path_to_go = session[:url] || root_path
          flash[:notice] = business.success_message
          redirect_to path_to_go
        else
          flash.now[:alert] = business.alert_message
          render_sudo_mode_form
        end
      end

      # GET /hello/sudo_mode/expire
      def expire
        business = Business::Authentication::SudoModeExpiration.new(current_access)
        business.expire!
        flash[:notice] = business.success_message
        redirect_to '/'
      end

      private

      def password_param
        params.require(:user)[:password]
      end
    end
  end
end

app/controllers/hello/concerns/authentication/sign_in.rb
module Hello
  module Concerns
    module Authentication
      module SignIn

        def on_success
          access_token = sign_in!(@sign_in.user, expires_at, sudo_mode_expires_at)

          respond_to do |format|
            format.html { redirect_to path_to_go }
            format.json { render json: access_token.as_json_web_api, status: :created }
          end
        end

        def on_failure
          respond_to do |format|
            format.html { render_sign_in }
            format.json { render json: @sign_in.errors, status: :unprocessable_entity }
          end
        end


        private

        def expires_at
          if params[:keep_me]
            30.days.from_now
          else
            30.minutes.from_now
          end
        end

        def sudo_mode_expires_at
          Hello.configuration.sudo_expires_in.from_now
        end

        def path_to_go
          session.delete(:url) || '/'
        end

      end
    end
  end
end

app/controllers/hello/concerns/management/forgot_password.rb
module Hello
  module Concerns
    module Management
      module ForgotPassword

        def on_success
          reset_token_and_deliver_emails!

          respond_to do |format|
            format.html { render_success }
            format.json { render json: { sent: true }, status: :created }
          end
        end

        def on_failure
          respond_to do |format|
            format.html { render_form }
            format.json { render json: @forgot_password.errors, status: :unprocessable_entity }
          end
        end

        private

        def reset_token_and_deliver_emails!
          url = get_reset_password_url

          emails.each do |email|
            Mailer.forgot_password(email, @user, url).deliver
          end
        end

        def emails
          @user.email_credentials.map(&:email)
        end

        def get_reset_password_url
          p      = @user.password_credential
          token  = p.reset_verifying_token!
          hello.reset_password_url(p.id, @user.id, token)
        end

      end
    end
  end
end

app/controllers/hello/concerns/management/reset_password.rb
module Hello
  module Concerns
    module Management
      module ResetPassword

        def on_success
          access_token = sign_in!(@reset_password.user, expires_at, sudo_mode_expires_at)

          redirect_to path_to_go
        end

        def on_failure
          render_reset_form
        end

        private

        def expires_at
          30.days.from_now
        end

        def sudo_mode_expires_at
          Hello.configuration.sudo_expires_in.from_now
        end

        def path_to_go
          '/'
        end

      end
    end
  end
end

app/controllers/hello/internationalization/locale_controller.rb
module Hello
  module Internationalization
    class LocaleController < ApplicationController
      dont_kick_people

      # GET /hello/locale
      def index
        respond_to do |format|
          format.html { render 'hello/internationalization/locales' }
          format.json { render json: { locales: view_context.available_locales_with_names } }
        end
      end

      # POST /hello/locale
      def update
        business = Business::Internationalization::UpdateLocale.new(params['locale'])

        current_user && current_user.update!(locale: business.locale)
        use_locale(business.locale)

        respond_to do |format|
          format.html { redirect_back fallback_location: root_path, notice: business.success_message }
          format.json { fail Hello::Errors::JsonNotSupported }
        end
      end
    end
  end
end

app/controllers/hello/management/accesses_controller.rb
module Hello
  module Management
    class AccessesController < ApplicationController
      kick :guest, :onboarding

      before_actions do
        all            { sudo_mode }
        only(:index)   { @accesses = current_user.accesses }
        only(:destroy) { @access = current_user.accesses.find(params[:id]) }
      end

      # GET /hello/accesses
      def index
        render 'hello/management/accesses'
      end

      # DELETE /hello/accesses/1
      def destroy
        business = Business::Management::UnlinkAccess.new
        if @access.destroy
          flash[:notice] = business.success_message
        else
          flash[:alert]  = business.alert_message
        end
        redirect_to hello.accesses_url
      end
    end
  end
end

app/controllers/hello/management/confirm_emails_controller.rb
module Hello
  module Management
    class ConfirmEmailsController < ApplicationController
      dont_kick_people

      before_actions do
        all { sign_out! }
        only(:confirm) { @credential = ::EmailCredential.where(id: params[:id]).first }
      end

      # GET /hello/emails/1/confirm/:token
      def confirm
        business = Business::Management::ConfirmEmail.new(@credential)

        if business.confirm_with_token(params[:token])
          _sign_in
          flash[:notice] = business.success_message
          redirect_to profile_path
        else
          flash[:alert] = business.alert_message
          redirect_to expired_confirmation_token_emails_path
        end
      end

      # GET /hello/emails/expired_confirmation_token
      def expired_confirmation_token
        render 'hello/management/email_credentials/expired_confirmation_token'
      end

      private

      def _sign_in
        # In RSpec and Capybara (Rails 4.2):
        # when the user gets access, the session of the next request will assume the values it had before,
        # if before you were a guest, you will be redirected as a user, but the following request will be as a guest again
        # if before you were a user1, you will be redirected as a user2, but the following request will be as a user1 again
        access_token = sign_in!(@credential.user, 1.hour.from_now)
      end
    end
  end
end

app/controllers/hello/management/emails_controller.rb
module Hello
  module Management
    class EmailsController < ApplicationController
      kick :guest, :onboarding
      sudo_mode

      helper_method :credentials

      before_actions do
        only(:index)  { @credential = ::EmailCredential.new }
        only(:create) { @credential = current_user.email_credentials.build(email_credential_params) }
        only(:destroy, :deliver) { @credential = current_user.email_credentials.find(params[:id]) }
      end

      # GET /hello/emails
      def index
        render_list
      end

      # POST /hello/emails
      def create
        business = Business::Management::AddEmail.new(@credential)
        if @credential.save
          redirect_to hello.emails_path, notice: business.success_message
        else
          flash.now[:alert] = business.error_message
          render_list
        end
      end

      # DELETE /hello/emails/1
      def destroy
        business = Business::Management::RemoveEmail.new(@credential)
        if @credential.destroy
          redirect_to hello.emails_path, notice: business.success_message
        else
          flash.now[:alert] = business.error_message
          render_list
        end
      end

      # POST /hello/emails/1/deliver
      def deliver
        business = Business::Management::SendConfirmationEmail.new(self, @credential)
        business.deliver
        flash[:notice] = business.success_message
        redirect_to hello.emails_path
      end

      private

      # Only allow a trusted parameter "white list" through.
      def email_credential_params
        params.require(:email_credential).permit(:email)
      end

      def credentials
        # TODO: this is necessary to hide a temporary bug, must solve this later
        current_user.credentials.where(type: 'EmailCredential')
      end

      def render_list
        render 'hello/management/email_credentials/index'
      end
    end
  end
end

app/controllers/hello/management/forgot_password_controller.rb
module Hello
  module Management
    # you really should be overriding concerns instead of this file
    class ForgotPasswordController < ApplicationController
      include Hello::Concerns::Management::ForgotPassword

      dont_kick :guest

      before_action { @sender = Hello.configuration.mailer_sender }

      # GET /hello/passwords/forgot
      def index
        @forgot_password = Business::Management::ForgotPassword.new
        render 'hello/management/password_credentials/forgot'
      end

      # POST /hello/passwords/forgot
      def forgot
        @forgot_password = Business::Management::ForgotPassword.new(params.require(:forgot_password))
        @user = @forgot_password.user

        if @forgot_password.reset
          on_success
        else
          on_failure
        end
      end

      private

      def render_success
        render 'hello/management/password_credentials/forgot_success'
      end

      def render_form
        render 'hello/management/password_credentials/forgot'
      end

    end
  end
end

app/controllers/hello/management/passwords_controller.rb
module Hello
  module Management
    class PasswordsController < ApplicationController
      kick :guest, :onboarding
      sudo_mode

      before_action do
        @password_credential = current_user.password_credential || fail(ActiveRecord::NotFound)
        @update_profile = Business::Management::UpdateProfile.new(@password_credential)
      end

      # GET /hello/passwords
      def index
        respond_to do |format|
          format.html { redirect_to password_path(@password_credential.id) }
          format.json { head :no_content }
        end
      end

      # GET /hello/passwords/1
      def show
        respond_to do |format|
          format.html { render_password_view }
          format.json { head :no_content }
        end
      end

      # PATCH /hello/passwords/1
      def update
        @password_credential.password = password_credential_params[:password]
        # @password_credential.password_confirmation = password_credential_params[:password_confirmation] if password_credential_params[:password_confirmation]

        if @password_credential.save
          respond_to do |format|
            format.html { redirect_to hello.password_path(@password_credential), notice: @update_profile.success_message }
            format.json { head :no_content }
          end
        else
          respond_to do |format|
            format.html { render_password_view }
            format.json { render json: @password_credential.errors, status: :unprocessable_entity }
          end
        end
      end

      private

      def password_credential_params
        params.require(:password_credential)
      end

      def render_password_view
        render 'hello/management/password_credentials/show'
      end
    end
  end
end

app/helpers/hello/application_helper.rb
# this gem requires this file to be here
module Hello
  module ApplicationHelper
  end
end

app/views/hello/authentication/_sign_in.html.erb
<%= form_for @sign_in, as: :sign_in, url: sign_in_path, html: {class: "form-horizontal", role: "form"} do |f| %>

  <!-- Errors -->
  <% if @sign_in.errors.any? %>
    <%= render '/hello/shared/errors', business: @sign_in %>
  <% end %>

  <div class="form-group">
    <%= f.label :login, "Email or Username", class: "col-sm-4 control-label" %>
    <div class="col-sm-4">
      <%= f.text_field :login, class: "form-control", placeholder: "Email or Username" %>

      <% if @sign_in.bad_login? %>
        <blockquote style="border-color: #a94442">
          <p class="text-danger">This login was not found in our database.</p>
          <p>Do you want to <%= link_to "Sign Up", hello.sign_up_path %> instead?</p>
        </blockquote>
      <% end %>

    </div>

  </div>


  <div class="form-group">
    <%= f.label :password, class: "col-sm-4 control-label" %>
    <div class="col-sm-4">
      <%= f.password_field :password, class: "form-control", placeholder: "Password" %>

      <% if @sign_in.bad_password? %>
        <blockquote style="border-color: #a94442">
          <p class="text-danger">Your password does not match that in our database.</p>
          <footer>
            Did you <%= link_to "forget your password", hello.forgot_passwords_path %>?
          </footer>
        </blockquote>
      <% end %>

    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-4">
      <div class="checkbox">
        <label>
          <%= check_box_tag :keep_me, '1', false %>
          Keep me signed in for <strong>30</strong> days
        </label>
      </div>
    </div>
  </div>
  <!--
  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-4">
      <%= link_to "I forgot my password", hello.forgot_passwords_path %>
    </div>
  </div>
 -->
  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-4">
      <%= f.submit "Sign In", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/hello/authentication/new_session.html.erb
<h1>Add Account</h1>

<p><%= link_to "Sign Up", hello.sign_up_path, class: 'btn btn-xs btn-info', style: 'width: 150px' %></li>
<p><%= link_to "Sign In", hello.sign_in_path, class: 'btn btn-xs btn-info', style: 'width: 150px' %></p>

app/views/hello/authentication/sessions.html.erb
<h1>Switch Accounts</h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Role</th>
      <th>Expiry</th>
      <th colspan="2">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @accesses.each do |a| %>
      <tr>
        <td><%= link_to a.user.username, a.user %></td>
        <td><%= a.user.name %></td>
        <td><%= a.user.role %></td>
        <td><%= distance_of_time_in_words_to_now(a.expires_at) %></td>
        <td><%= link_to "Switch!",
                        hello.session_path(a.id),
                        class: 'btn btn-xs btn-block btn-success' unless is_current_access?(a) %></td>
        <td><%= button_to "Forget",
                          hello.session_path(a.id),
                          method: :delete,
                          class: 'btn btn-xs btn-block btn-danger',
                          data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <tr>
      <td colspan="4"></td>
      <td colspan="2"><%= link_to "Add Account", hello.new_session_path, class: 'btn btn-xs btn-block btn-info' %></td>
    </tr>
  </tbody>
</table>

app/views/hello/authentication/sign_in.html.erb
<h2 class="page-header">Sign In</h2>

<%= render 'hello/authentication/sign_in' %>

app/views/hello/authentication/sudo_mode.html.erb
<div class="row">
<%= render '/hello/shared/settings' %>

<div class="col-sm-3-offset col-md-2-offset col-sm-9 col-md-10">
<div class="panel panel-danger">
  <div class="panel-heading">Confirm Password to Continue</div>
  <div class="panel-body">

<%= form_for current_user, url: hello.sudo_mode_path, html: {class: "form-horizontal", role: "form"} do |f| %>

  <div class="form-group">
    <%= f.label :username, class: "col-sm-4 control-label" %>
    <div class="col-sm-4">
      <span class="form-control" style="border: 0px; box-shadow: none">
        <%= current_user.username %>
      </span>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password, class: "col-sm-4 control-label" %>
    <div class="col-sm-4">
      <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-4 col-sm-4">
      <%= f.submit "Confirm Password", class: "btn btn-danger" %>
    </div>
  </div>
<% end %>
  </div>

</div>
</div>

</div>